# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('delay', models.IntegerField(verbose_name='Minutes')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
        migrations.AlterIndexTogether(
            name='reminder',
            index_together=set([('id',)]),
        ),
    ]
